"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"
import { LANGUAGE_COOKIE, LANGUAGE_COOKIE_MAX_AGE, isSupportedLanguage, resolveLanguage } from "@/lib/i18n"
import type { SupportedLanguage } from "@/lib/i18n"

type Language = SupportedLanguage

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.profile": "My Profile",
    "dashboard.nav.dashboard": "Dashboard",
    "dashboard.nav.sessions": "Sessions",
    "dashboard.nav.settings": "Settings",
    "dashboard.nav.logout": "Logout",

    // Student Dashboard
    "dashboard.student.hero.badge": "Personalized view",
    "dashboard.student.hero.control": "Control Center",
    "dashboard.student.hero.point1": "Keep exploring tutors that match your study goals and bookmark your favorites.",
    "dashboard.student.hero.point2": "Rate completed sessions to help peers find great mentors faster.",
    "dashboard.student.hero.point3": "Use quick actions to jump into bookings, messages, or tutor search.",
    "dashboard.student.hero.ctaReview": "Review Sessions",
    "dashboard.student.hero.ctaFindTutor": "Find a Tutor",
    "dashboard.student.hero.spotlightSubtitle": "Track what's coming next and what needs your attention.",
    "dashboard.student.hero.spotlightNext": "Next session",
    "dashboard.student.hero.spotlightPending": "Pending approvals",
    "dashboard.student.hero.spotlightChecklist": "Essential steps",
    "dashboard.student.hero.checklistProfile": "Complete your profile to unlock better matches.",
    "dashboard.student.hero.checklistBook": "Book your next tutor early to stay ahead.",
    "dashboard.student.hero.checklistReview": "Review finished sessions to help peers.",
    "dashboard.student.stats.active": "Active Sessions",
    "dashboard.student.stats.hours": "Learning Hours",
    "dashboard.student.stats.completed": "Completed Sessions",
    "dashboard.student.stats.favorite": "Favorite Tutors",
    "dashboard.student.cards.next": "Next on your calendar",
    "dashboard.student.cards.pending": "Pending approvals",
    "dashboard.student.cards.streak": "Learning streak",
    "dashboard.student.cards.nextEmpty": "No upcoming sessions scheduled.",
    "dashboard.student.cards.pendingClear": "All session requests are confirmed.",
    "dashboard.student.cards.viewBooking": "View booking",
    "dashboard.student.cards.browseTutors": "Browse tutors",
    "dashboard.student.cards.manageRequests": "Manage requests",
    "dashboard.student.cards.viewHistory": "View history",
    "dashboard.student.actions.title": "Quick Actions",
    "dashboard.student.actions.findTutor": "Find a Tutor",
    "dashboard.student.actions.viewSessions": "View All Sessions",
    "dashboard.student.actions.messages": "Messages",
    "dashboard.student.upcoming.title": "Upcoming & Pending Sessions",
    "dashboard.student.upcoming.description": "Here are your scheduled and requested sessions.",
    "dashboard.student.upcoming.tutor": "Tutor",
    "dashboard.student.upcoming.subject": "Subject",
    "dashboard.student.upcoming.datetime": "Date & Time",
    "dashboard.student.upcoming.status": "Status",
    "dashboard.student.upcoming.actions": "Actions",
    "dashboard.student.upcoming.empty": "You have no upcoming sessions.",
    "dashboard.student.upcoming.viewDetails": "View Details",
    "dashboard.student.upcoming.join": "Join Session",
    "dashboard.student.upcoming.cancel": "Cancel",
    "dashboard.student.upcoming.findTutor": "Find a Tutor",
    "dashboard.student.upcoming.cancelConfirm": "Are you sure you want to cancel this session?",
    "dashboard.student.upcoming.cancelSuccess": "Session cancelled successfully.",
    "dashboard.student.upcoming.cancelError": "Failed to cancel session.",
    "dashboard.student.reviews.title": "Rate Recent Sessions",
    "dashboard.student.reviews.description": "Review your past sessions to help others.",
    "dashboard.student.reviews.none": "No completed sessions yet.",
    "dashboard.student.reviews.rate": "Rate Session",
    "dashboard.student.reviews.reviewWith": "Review your session with {{name}}",
    "dashboard.student.reviews.feedback": "Your feedback is valuable.",
    "dashboard.student.reviews.rating": "Rating",
    "dashboard.student.reviews.comment": "Comment",
    "dashboard.student.reviews.placeholder": "Tell us about your experience...",
    "dashboard.student.reviews.submit": "Submit Review",
    "dashboard.student.reviews.submitting": "Submitting...",
    "dashboard.student.reviews.success": "Review submitted successfully!",
    "dashboard.student.reviews.error": "Failed to submit review.",
    "dashboard.teacher.profileSettings": "Profile settings",
    "dashboard.teacher.profileSubtitle": "Keep your teacher profile up to date for students.",
    "dashboard.teacher.prefix": "Prefix",
    "dashboard.teacher.prefixPlaceholder": "Select a prefix",
    "dashboard.teacher.firstName": "First name",
    "dashboard.teacher.middleName": "Middle name",
    "dashboard.teacher.familyName": "Family name",
    "dashboard.teacher.phone": "Phone number",
    "dashboard.teacher.email": "Email",
    "dashboard.teacher.bio": "Short bio",
    "dashboard.teacher.photoLabel": "Profile photo",
    "dashboard.teacher.photoSelected": "Selected file",
    "dashboard.teacher.photoUpload": "Upload photo",
    "dashboard.teacher.photoReplace": "Replace photo",
    "dashboard.teacher.photoRemove": "Remove photo",
    "dashboard.teacher.photoHelper": "This image appears on your tutor card once the admin team approves your profile.",
    "dashboard.teacher.photoAlt": "Teacher avatar",
    "dashboard.teacher.saving": "Saving...",
    "dashboard.teacher.updateProfile": "Update profile",
    "dashboard.teacher.profileUpdated": "Profile details updated",
    "dashboard.teacher.subjectFormTitle": "Register a new subject",
    "dashboard.teacher.subjectFormSubtitle": "Showcase the topics and achievements you can guide students through.",
    "dashboard.teacher.subjectApprovalNote": "Subjects become visible to students once the PeerEdu team validates the uploaded grades.",
    "dashboard.teacher.subjectName": "Subject name",
    "dashboard.teacher.subjectCode": "Subject code",
    "dashboard.teacher.college": "College / university",
    "dashboard.teacher.grade": "Grade achieved",
    "dashboard.teacher.subjectListTitle": "Registered subjects",
    "dashboard.teacher.subjectSubmit": "Add subject",
    "dashboard.teacher.subjectAdded": "Subject added to your profile",
    "dashboard.teacher.subjectVerification.identity": "My name, college ID, and college name appear on the uploaded proof.",
    "dashboard.teacher.subjectVerification.grade": "I confirm the grade shown is accurate and issued by my college.",
    "dashboard.teacher.subjectVerification.helper": "Ensure the document shows your college name and academic year.",
    "dashboard.teacher.subjectVerification.error": "Please confirm both statements before adding a subject.",
    "dashboard.teacher.gradeProof": "Upload proof of grade",
    "dashboard.teacher.gradeProof.helper": "Attach a PDF or clear screenshot that shows this course grade (PDF/JPG/PNG, max 10MB).",
    "dashboard.teacher.gradeProof.selected": "Selected file",
    "dashboard.teacher.gradeProof.error": "Please upload a grade report before adding this subject.",
    "dashboard.teacher.availabilityTitle": "Weekly availability",
    "dashboard.teacher.availabilityHelper": "Set the time slots students can book with you.",
    "dashboard.teacher.quickActions": "Quick Actions",
    "dashboard.teacher.quickActions.settings": "Settings",
    "dashboard.teacher.quickActions.availability": "Manage Availability",
    "dashboard.teacher.quickActions.sessions": "View All Sessions",
    "dashboard.teacher.quickActions.analytics": "Detailed Analytics",
    "dashboard.teacher.hero.badge": "Teacher dashboard",
    "dashboard.teacher.hero.welcome": "Welcome back, {{name}}.",
    "dashboard.teacher.hero.subtitle": "Keep an eye on new requests, upcoming commitments, and your growth across PeerEdu.",
    "dashboard.teacher.hero.registerCta": "Register subjects",
    "dashboard.teacher.hero.spotlightTitle": "Teaching spotlight",
    "dashboard.teacher.hero.spotlightStatus": "Awaiting approval",
    "dashboard.teacher.hero.spotlightDescription":
      "Subjects appear here once the admin team validates the grade reports you upload. Submit your transcripts under settings to unlock this section.",
    "dashboard.teacher.hero.pendingBadge": "Pending",
    "dashboard.teacher.hero.manageProfile": "Manage profile",
    "dashboard.teacher.hero.registerSubjects": "Register subjects",
    "dashboard.teacher.stats.requests": "New Requests",
    "dashboard.teacher.stats.requestsHelper": "Awaiting reply",
    "dashboard.teacher.stats.upcoming": "Upcoming Sessions",
    "dashboard.teacher.stats.upcomingHelper": "Next 7 days",
    "dashboard.teacher.stats.total": "Total Sessions",
    "dashboard.teacher.stats.totalHelper": "Completed",
    "dashboard.teacher.stats.subjects": "My Subjects",
    "dashboard.teacher.stats.subjectsApproved": "Approved subjects",
    "dashboard.teacher.stats.subjectsPending": "Will appear after admin approval",
    "dashboard.teacher.stats.pendingValue": "Pending",
    "dashboard.teacher.stats.rating": "Your Rating",
    "dashboard.teacher.stats.ratingHelper": "Out of 5",
    "dashboard.teacher.stats.earnings": "Projected Earnings",
    "dashboard.teacher.stats.earningsHelper": "OMR",
    "dashboard.teacher.profileUpdateError": "Unable to update your profile. Please try again.",
    "dashboard.teacher.settings.title": "Teacher Settings",
    "dashboard.teacher.settings.subtitle": "Fine tune your teaching profile and keep your expertise front and center.",
    "dashboard.teacher.preferences.title": "Teaching preferences",
    "dashboard.teacher.preferences.description": "Keep students informed about your availability and learning style.",
    "dashboard.teacher.preferences.point1": "Update your time slots from the availability manager.",
    "dashboard.teacher.preferences.point2": "Use subject registration to highlight your strongest tracks.",
    "dashboard.teacher.preferences.point3": "Keep your profile photo and bio consistent across languages.",
    "availability.heading": "Manage Availability",
    "availability.day.sunday": "Sunday",
    "availability.day.monday": "Monday",
    "availability.day.tuesday": "Tuesday",
    "availability.day.wednesday": "Wednesday",
    "availability.day.thursday": "Thursday",
    "availability.day.friday": "Friday",
    "availability.day.saturday": "Saturday",
    "availability.empty": "No slots yet",
    "availability.dialog.add": "Add availability",
    "availability.dialog.edit": "Edit availability",
    "availability.dialog.start": "Start time",
    "availability.dialog.end": "End time",
    "availability.dialog.cancel": "Cancel",
    "availability.dialog.save": "Save slot",
    "availability.dialog.deleteTitle": "Delete this availability?",
    "availability.dialog.deleteDescription": "This action cannot be undone. This will permanently remove the selected time slot.",
    "availability.dialog.deleteConfirm": "Delete",
    "availability.error.missing": "Please enter both a start time and an end time.",
    "availability.error.order": "End time must be later than the start time.",
    "availability.toast.saveSuccess": "Availability slot saved.",
    "availability.toast.saveError": "Unable to save the availability slot.",
    "availability.toast.updateSuccess": "Availability slot updated.",
    "availability.toast.updateError": "Unable to update the availability slot.",
    "availability.toast.deleteSuccess": "Availability slot removed.",
    "availability.toast.deleteError": "Unable to delete the availability slot.",

    // Hero Section
    "hero.title": "Connect. Learn. Excel.",
    "hero.subtitle":
      "PeerEdu connects university students with academic excellence. Find expert tutors or share your knowledge while earning - all within a trusted peer-to-peer learning community.",
    "hero.cta.primary": "Get Started",
    "hero.cta.secondary": "Learn More",

    // How It Works Section
    "works.title": "How PeerEdu Works",
    "works.subtitle": "Simple, secure, and effective peer-to-peer learning",
    "works.connect.title": "Connect",
    "works.connect.desc": "Find the perfect tutor or student match based on your academic needs and schedule",
    "works.learn.title": "Learn",
    "works.learn.desc": "Engage in personalized tutoring sessions designed to help you excel in your studies",
    "works.excel.title": "Excel",
    "works.excel.desc": "Achieve your academic goals while building lasting connections with fellow students",

    // Features Section
    "features.title": "Why Choose PeerEdu?",
    "features.subtitle": "Built by students, for students - with features that matter",
    "features.expert.title": "Expert Tutors",
    "features.expert.desc": "Connect with academically excellent students who excel in their subjects",
    "features.flexible.title": "Flexible Scheduling",
    "features.flexible.desc": "Book sessions that fit your schedule with easy-to-use booking system",
    "features.secure.title": "Safe & Secure",
    "features.secure.desc": "Verified student profiles and secure payment system for peace of mind",

    // Mission, Vision, Message
    "message.title": "Our Message",
    "message.content":
      "Education is most powerful when shared. We believe every student has something valuable to teach and learn. PeerEdu creates a community where knowledge flows freely, fostering academic excellence and meaningful connections.",
    "vision.title": "Our Vision",
    "vision.content":
      "To become the leading peer-to-peer learning platform in the Middle East, empowering students to achieve academic excellence through collaborative learning and knowledge sharing.",
    "mission.title": "Our Mission",
    "mission.content":
      "To connect university students across Oman, creating opportunities for peer-to-peer learning, academic support, and personal growth while fostering a culture of knowledge sharing and collaboration.",

    // CEO Section
    "ceo.title": "Meet Our CEO",
    "ceo.subtitle": "Leading the vision for peer-to-peer education in Oman",
    "ceo.name": "Mohammed Ashraf",
    "ceo.position": "Founder & CEO",
    "ceo.bio1":
      "Mohammed holds a Bachelor's degree in Software Application Development from UTAS Ibri College. With a passion for education technology and student empowerment, he founded PeerEdu to bridge the gap between students seeking academic support and those excelling in their studies.",
    "ceo.bio2":
      "His vision is to create a sustainable ecosystem where knowledge sharing becomes a natural part of university life, helping students not only achieve academic success but also develop leadership and mentoring skills that will serve them throughout their careers.",

    // CTA Section
    "cta.title": "Ready to Start Learning?",
    "cta.subtitle":
      "Join thousands of students already using PeerEdu to excel in their studies. Whether you need help or want to help others, we've got you covered.",
    "cta.student": "Join as Student",
    "cta.tutor": "Become a Tutor",

    // Login Page
    "login.title": "Sign In",
    "login.subtitle": "Access your PeerEdu account to continue your learning journey",
    "login.form.title": "Login to your account",
    "login.form.description": "Enter your email and password to access your account",
    "login.email": "University Email",
    "login.password": "Password",
    "login.remember": "Remember me",
    "login.forgot": "Forgot password?",
    "login.submit": "Sign In",
    "login.loading": "Signing you in...",
    "login.signup": "Don't have an account? Sign up here",

    // Register Page
    "register.title": "Create Account",
    "register.subtitle": "Start your peer learning journey today",
    "register.form.title": "Sign up for PeerEdu",
    "register.form.description": "Create your account to connect with fellow students",
    "register.role.title": "Registering as",
    "register.role.student": "Student",
    "register.role.teacher": "Teacher",
    "register.firstName": "First Name",
    "register.middleName": "Middle Name",
    "register.familyName": "Family Name",
    "register.phone": "Phone Number",
    "register.email": "Educational Email",
    "register.university": "College/University",
    "register.yearOfStudy": "Year of Study",
    "register.password": "Password",
    "register.confirmPassword": "Confirm Password",
    "register.terms": "I agree to the Terms of Service and Privacy Policy",
    "register.submit": "Register",
    "register.loading": "Creating your account...",
    "register.signin": "Already have an account? Sign in here",
    "register.continue": "Or continue with",
    "register.google": "Google",
    "register.twitter": "Twitter",
    "register.placeholder.firstName": "First name",
    "register.placeholder.middleName": "Middle name",
    "register.placeholder.familyName": "Family name",
    "register.placeholder.phone": "+968",
    "register.placeholder.email": "Enter your educational email",
    "register.placeholder.university": "Select your college/university",
    "register.placeholder.yearOfStudy": "Select your year of study",
    "register.placeholder.password": "Create a password",
    "register.placeholder.confirmPassword": "Confirm your password",
    "register.gradeUpload": "Upload your latest grade report",
    "register.gradeUpload.helper": "Accepted formats: PDF or a clear image (max 10MB).",
    "register.gradeUpload.selected": "Selected file",
    "register.checkbox.gradeAuthentic": "I confirm this grade report is genuine and issued by my college.",
    "register.checkbox.gradeIdentity": "My full name and student ID appear on the uploaded report.",
    "register.checkbox.reportDetails": "Make sure your college name and academic year are visible in the document.",
    "register.university.utas": "UTAS Ibri",
    "register.university.squ": "Sultan Qaboos University",
    "register.university.german": "German University of Technology",
    "register.university.nizwa": "University of Nizwa",
    "register.university.dhofar": "Dhofar University",
    "register.university.muscat": "Muscat University",
    "register.university.oman": "University of Oman",
    "register.university.utas.ibri": "UTAS Ibri",
    "register.university.utas.muscat": "UTAS Muscat",
    "register.university.utas.sohar": "UTAS Sohar",
    "register.university.utas.salalah": "UTAS Salalah",
    "register.university.utas.nizwa": "UTAS Nizwa",
    "register.university.utas.general": "UTAS (General)",
    "register.university.utas.shinas": "UTAS Shinas",
    "register.university.utas.sur": "UTAS Sur",
    "register.university.utas.almusannah": "UTAS Al Musannah",
    "register.university.utas.ibra": "UTAS Ibra",
    "register.university.utas.rustaq": "UTAS Rustaq",
    "register.university.buraimi": "University of Buraimi",
    "register.university.sohar": "Sohar University",
    "register.university.asharqiyah": "A'Sharqiyah University",
    "register.university.national": "National University of Science & Technology",
    "register.university.majan": "Majan University College",
    "register.university.modern": "Modern College of Business & Science",
    "register.university.middleeast": "Middle East College",
    "register.university.arabopen": "Arab Open University - Oman",
    "register.university.tourism": "Oman Tourism College",
    "register.university.healthsciences": "Oman College of Health Sciences",
    "register.university.maritime": "International Maritime College Oman",
    "register.university.dental": "Oman Dental College",
    "register.university.alzahra": "Al Zahra College for Women",
    "register.university.gulf": "Gulf College",
    "register.university.bayan": "Bayan College",
    "register.university.law": "Oman College of Law",
    "register.university.other": "Other",
    "register.year.foundation1": "Foundation Level 1",
    "register.year.foundation2": "Foundation Level 2",
    "register.year.foundation3": "Foundation Level 3",
    "register.year.foundation4": "Foundation Level 4",
    "register.year.study1": "Year 1",
    "register.year.study2": "Year 2",
    "register.year.study3": "Year 3",
    "register.year.study4": "Year 4",
    "register.year.graduate": "Fresh Graduate",

    // Tutors Page
    "tutors.nav.back": "Back to dashboard",
    "tutors.nav.tagline": "Tutor search",
    "tutors.hero.badge": "Smart match",
    "tutors.title": "Find tutors by college and subject",
    "tutors.subtitle": "Select your college, add the subject code, and connect with tutors who already know the material.",
    "tutors.hero.hint": "Need a better match?",
    "tutors.hero.hintDetail": "Adjust the filters anytime for instant updates.",
    "tutors.filters.title": "Filter tutors",
    "tutors.filters.description": "Choose your college, then add the subject details.",
    "tutors.filters.university": "College",
    "tutors.filters.university.placeholder": "Choose a college",
    "tutors.filters.subjectCode": "Subject code",
    "tutors.filters.subjectCode.placeholder": "e.g., ENG201",
    "tutors.filters.subjectName": "Subject name",
    "tutors.filters.subjectName.placeholder": "e.g., Academic Writing",
    "tutors.filters.teacherName": "Teacher name",
    "tutors.filters.teacherName.placeholder": "e.g., Ali Al Habsi",
    "tutors.filters.optional": "Optional",
    "tutors.mobile.button": "Filters",
    "tutors.mobile.title": "Refine tutors",
    "tutors.results.preheading": "Matching list",
    "tutors.results.heading": "Available tutors",
    "tutors.results.caption": "Results refresh automatically when you edit the filters.",
    "tutors.results.error.title": "Unable to load tutors",
    "tutors.results.error.description": "Please refresh or update the filters and try again.",
    "tutors.results.empty.title": "No tutors match this search",
    "tutors.results.empty.description": "Change the college or subject details to see more tutors.",
    "tutors.results.showing": "Showing",
    "tutors.results.of": "of",
    "tutors.results.tutors": "tutors",
    "tutors.pagination.prev": "Previous page",
    "tutors.pagination.next": "Next page",
    "tutor.card.reviews": "reviews",
    "tutor.card.perHour": "per hour",
    "tutor.card.sessionSummary.prefix": "Based on",
    "tutor.card.sessionSummary.suffix": "completed sessions.",
    "tutor.card.viewProfile": "View profile",
    "tutor.card.bookNow": "Book now",

    // About Page
    "about.badge": "About PeerEdu",
    "about.title": "Empowering Students Through Peer Learning",
    "about.subtitle":
      "Founded with the belief that the best learning happens when students teach students, PeerEdu is revolutionizing education in Oman by creating meaningful connections between university students.",
    "about.story.title": "Our Story",
    "about.story.subtitle": "How PeerEdu came to life",
    "about.story.p1":
      "PeerEdu was born from a simple observation: university students often struggle to find the right academic support, while many talented students have knowledge to share but lack the platform to do so effectively.",
    "about.story.p2":
      "Our founder, Mohammed Ashraf, experienced this firsthand during his studies in Software Application Development at UTAS Ibri College. He noticed that peer-to-peer learning was not only more relatable and accessible but often more effective than traditional tutoring methods.",
    "about.story.p3":
      "Today, PeerEdu serves as a bridge connecting students across Oman, fostering a community where academic excellence is achieved through collaboration, mutual support, and shared knowledge.",
    "about.foundation.title": "Our Foundation",
    "about.foundation.subtitle": "The principles that guide everything we do",
    "about.mission.title": "Mission",
    "about.mission.content":
      "To connect university students across Oman, creating opportunities for peer-to-peer learning, academic support, and personal growth while fostering a culture of knowledge sharing and collaboration.",
    "about.vision.title": "Vision",
    "about.vision.content":
      "To become the leading peer-to-peer learning platform in the Middle East, empowering students to achieve academic excellence through collaborative learning and knowledge sharing.",
    "about.values.title": "Values",
    "about.values.content":
      "Excellence, collaboration, integrity, and accessibility. We believe education should be inclusive, supportive, and driven by genuine care for student success.",
    "about.different.title": "What Makes Us Different",
    "about.different.subtitle": "Why students choose PeerEdu over traditional tutoring",
    "about.peer.title": "Peer-to-Peer Connection",
    "about.peer.desc": "Learn from fellow students who recently mastered the same concepts you're struggling with",
    "about.flexible.title": "Flexible & Affordable",
    "about.flexible.desc": "More affordable than professional tutoring with scheduling that works around student life",
    "about.safe.title": "Safe & Verified",
    "about.safe.desc": "All tutors are verified university students with proven academic excellence",
    "about.expertise.title": "Subject Expertise",
    "about.expertise.desc": "Find tutors who excel in your specific courses and understand your curriculum",
    "about.results.title": "Proven Results",
    "about.results.desc": "Students report improved grades and better understanding through peer learning",
    "about.growth.title": "Mutual Growth",
    "about.growth.desc": "Both tutors and students benefit - learn while earning, teach while reinforcing knowledge",
    "about.leadership.title": "Leadership",
    "about.leadership.subtitle": "Meet the team behind PeerEdu",
    "about.ceo.bio1":
      "Mohammed holds a Bachelor's degree in Software Application Development from UTAS Ibri College. His academic journey sparked the idea for PeerEdu when he realized the untapped potential of peer-to-peer learning in university settings.",
    "about.ceo.bio2":
      "With a deep understanding of both technology and education, Mohammed combines his technical expertise with his passion for student empowerment to create innovative solutions that make learning more accessible and effective.",
    "about.ceo.bio3":
      "His vision extends beyond just connecting students - he aims to build a sustainable ecosystem where knowledge sharing becomes an integral part of university culture, preparing students not just for academic success but for lifelong learning and leadership.",
    "about.impact.title": "Our Impact",
    "about.impact.subtitle": "Growing community of students helping students succeed",
    "about.stats.students": "Active Students",
    "about.stats.sessions": "Sessions Completed",
    "about.stats.subjects": "Subjects Covered",
    "about.stats.satisfaction": "Satisfaction Rate",
    "about.join.title": "Join Our Community",
    "about.join.subtitle":
      "Be part of the peer learning revolution. Whether you need help or want to help others, PeerEdu is your platform for academic success.",
    "about.join.cta": "Get Started Today",
    "about.join.back": "Back to Home",

    // Footer
    "footer.contact": "Contact Us",
    "footer.description": "Connecting university students for peer-to-peer learning and academic excellence.",
    "footer.support": "Support",
    "footer.faq": "FAQ",
    "footer.policy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.rights": "© 2025 PeerEdu. All rights reserved.",
    "footer.followUs": "Follow Us",

    // Forgot Password Page
    "forgotPassword.title": "Forgot Password",
    "forgotPassword.subtitle": "Enter your email to receive a reset link",
    "forgotPassword.email": "Email",
    "forgotPassword.submit": "Send Reset Link",
    "forgotPassword.loading": "Sending...",
    "forgotPassword.success.title": "Check Your Email",
    "forgotPassword.success.message":
      "A password reset link has been sent to your email address. Please check your inbox.",
    "forgotPassword.backToLogin": "Back to Login",

    // Reset Password Page
    "resetPassword.title": "Reset Your Password",
    "resetPassword.subtitle": "Create a new, strong password for your account.",
    "resetPassword.password": "New Password",
    "resetPassword.confirmPassword": "Confirm New Password",
    "resetPassword.submit": "Set New Password",
    "resetPassword.loading": "Resetting...",
    "resetPassword.success.title": "Password Reset!",
    "resetPassword.success.message":
      "Your password has been changed successfully. You can now log in.",
    "resetPassword.goToLogin": "Go to Login",
    "resetPassword.invalid.title": "Invalid Link",
    "resetPassword.invalid.message":
      "This password reset link is invalid or has expired. Please request a new one.",
    "resetPassword.invalid.requestNew": "Request New Link",
    "resetPassword.strength.weak": "Weak",
    "resetPassword.strength.medium": "Medium",
    "resetPassword.strength.strong": "Strong",
    "resetPassword.error.mismatch": "Passwords do not match",
    "resetPassword.error.length": "Password must be at least 8 characters",
    "resetPassword.error.case": "Must contain an uppercase letter",
    "resetPassword.error.number": "Must contain a number",
    "resetPassword.error.special": "Must contain a special character",

    // Password Changed Email
    "passwordChanged.subject": "Your PeerEdu Password Has Been Changed",
    "passwordChanged.title": "Password Changed Successfully",
    "passwordChanged.greeting": "Hi {name},",
    "passwordChanged.message":
      "This email confirms that the password for your PeerEdu account has been successfully changed.",
    "passwordChanged.warning":
      "If you were not the one who made this change, please contact our support team immediately to secure your account.",
    "passwordChanged.contactSupport": "Contact Support",

    // Admin Dashboard
    "admin.dashboard.title": "Admin Dashboard",
    "admin.dashboard.subtitle": "Overview of the PeerEdu platform.",
    "admin.stats.totalUsers": "Total Users",
    "admin.stats.students": "Students",
    "admin.stats.teachers": "Teachers",
    "admin.stats.admins": "Admins",
    "admin.stats.approvedTutors": "Approved Tutors",
    "admin.stats.pendingTutors": "Pending Tutors",
    "admin.stats.totalBookings": "Total Bookings",
    "admin.stats.pending": "Pending",
    "admin.stats.confirmed": "Confirmed",
    "admin.stats.completed": "Completed",
    "admin.stats.cancelled": "Cancelled",
    "admin.stats.totalRevenue": "Total Revenue",
    "admin.stats.userGrowth": "User Growth (30d)",
    "admin.pendingApprovals.title": "Pending Teacher Approvals",
    "admin.pendingApprovals.tutor": "Tutor",
    "admin.pendingApprovals.university": "University",
    "admin.pendingApprovals.subjects": "Subjects",
    "admin.pendingApprovals.rate": "Rate",
    "admin.pendingApprovals.registered": "Registered",
    "admin.pendingApprovals.actions": "Actions",
    "admin.pendingApprovals.viewProfile": "View Full Profile",
    "admin.pendingApprovals.approve": "Approve",
    "admin.pendingApprovals.reject": "Reject",
    "admin.pendingApprovals.empty": "No tutor applications awaiting review.",
    "admin.pendingStudents.title": "Pending Student Accounts",
    "admin.pendingStudents.description": "Review and activate new student profiles.",
    "admin.pendingStudents.name": "Student",
    "admin.pendingStudents.email": "Email",
    "admin.pendingStudents.university": "University",
    "admin.pendingStudents.joined": "Joined",
    "admin.pendingStudents.actions": "Actions",
    "admin.pendingStudents.empty": "No student accounts are waiting for approval.",
    "admin.subjectApprovals.title": "Subject Registrations",
    "admin.subjectApprovals.description": "Teachers awaiting validation of their submitted subjects.",
    "admin.subjectApprovals.empty": "No subject requests are pending right now.",
    "admin.subjectApprovals.noteLabel": "Internal note",
    "admin.subjectApprovals.notePlaceholder": "Optional note for the tutor (visible internally)",
    "admin.emptyState.generic": "Nothing to review here yet.",
    "admin.recentUsers.title": "Recent Users",
    "admin.recentUsers.name": "Name",
    "admin.recentUsers.email": "Email",
    "admin.recentUsers.role": "Role",
    "admin.recentUsers.joined": "Joined",
    "admin.recentBookings.title": "Recent Bookings",
    "admin.recentBookings.student": "Student",
    "admin.recentBookings.tutor": "Tutor",
    "admin.recentBookings.status": "Status",
    "admin.recentBookings.date": "Date",
    "admin.charts.userGrowthTitle": "New Users (Last 30 Days)",
    "admin.charts.bookingsStatusTitle": "Bookings by Status",
    "admin.charts.revenueTitle": "Revenue (Last 7 Days)",
    "admin.quickActions.title": "Quick Actions",
    "admin.quickActions.manageUsers": "Manage Users",
    "admin.quickActions.manageTutors": "Manage Tutors",
    "admin.quickActions.allBookings": "All Bookings",
    "admin.quickActions.reports": "Reports",
    "admin.quickActions.settings": "Settings",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب",
    "nav.profile": "ملفي الشخصي",
    "dashboard.nav.dashboard": "لوحة التحكم",
    "dashboard.nav.sessions": "الجلسات",
    "dashboard.nav.settings": "الإعدادات",
    "dashboard.nav.logout": "تسجيل الخروج",

    // Student Dashboard
    "dashboard.student.hero.badge": "عرض مخصص",
    "dashboard.student.hero.control": "مركز التحكم",
    "dashboard.student.hero.point1": "واصل استكشاف المعلمين الذين يطابقون أهدافك الدراسية واحتفظ بالمفضلين لديك.",
    "dashboard.student.hero.point2": "قيّم الجلسات المكتملة لمساعدة زملائك على إيجاد المرشدين الرائعين بسرعة.",
    "dashboard.student.hero.point3": "استخدم الإجراءات السريعة للانتقال مباشرة إلى الحجوزات أو الرسائل أو البحث عن معلم.",
    "dashboard.student.hero.ctaReview": "مراجعة الجلسات",
    "dashboard.student.hero.ctaFindTutor": "ابحث عن معلم",
    "dashboard.student.hero.spotlightSubtitle": "تابع الجلسات القادمة والمتطلبات الأساسية في مكان واحد.",
    "dashboard.student.hero.spotlightNext": "الجلسة التالية",
    "dashboard.student.hero.spotlightPending": "الطلبات المعلقة",
    "dashboard.student.hero.spotlightChecklist": "خطوات أساسية",
    "dashboard.student.hero.checklistProfile": "أكمل ملفك الدراسي لتحصل على تطابقات أفضل.",
    "dashboard.student.hero.checklistBook": "احجز جلسة الدعم التالية مبكرًا للبقاء متقدمًا.",
    "dashboard.student.hero.checklistReview": "قيّم الجلسات المنتهية لمساعدة زملائك.",
    "dashboard.student.stats.active": "جلسات حالية",
    "dashboard.student.stats.hours": "ساعات التعلم",
    "dashboard.student.stats.completed": "جلسات مكتملة",
    "dashboard.student.stats.favorite": "المعلمون المفضلون",
    "dashboard.student.cards.next": "ما التالي في جدولك",
    "dashboard.student.cards.pending": "طلبات قيد الموافقة",
    "dashboard.student.cards.streak": "سلسلة التعلم",
    "dashboard.student.cards.nextEmpty": "لا توجد جلسات قادمة حالياً.",
    "dashboard.student.cards.pendingClear": "تمت معالجة جميع الطلبات.",
    "dashboard.student.cards.viewBooking": "عرض الحجز",
    "dashboard.student.cards.browseTutors": "استعرض المعلمين",
    "dashboard.student.cards.manageRequests": "إدارة الطلبات",
    "dashboard.student.cards.viewHistory": "سجل الجلسات",
    "dashboard.student.actions.title": "إجراءات سريعة",
    "dashboard.student.actions.findTutor": "ابحث عن معلم",
    "dashboard.student.actions.viewSessions": "عرض كل الجلسات",
    "dashboard.student.actions.messages": "الرسائل",
    "dashboard.student.upcoming.title": "الجلسات القادمة والمعلقة",
    "dashboard.student.upcoming.description": "هنا يمكنك متابعة الجلسات المجدولة وطلباتك قيد المراجعة.",
    "dashboard.student.upcoming.tutor": "المعلم",
    "dashboard.student.upcoming.subject": "المادة",
    "dashboard.student.upcoming.datetime": "التاريخ والوقت",
    "dashboard.student.upcoming.status": "الحالة",
    "dashboard.student.upcoming.actions": "إجراءات",
    "dashboard.student.upcoming.empty": "لا توجد جلسات قادمة حالياً.",
    "dashboard.student.upcoming.viewDetails": "عرض التفاصيل",
    "dashboard.student.upcoming.join": "الانضمام للجلسة",
    "dashboard.student.upcoming.cancel": "إلغاء",
    "dashboard.student.upcoming.findTutor": "ابحث عن معلم",
    "dashboard.student.upcoming.cancelConfirm": "هل أنت متأكد من إلغاء هذه الجلسة؟",
    "dashboard.student.upcoming.cancelSuccess": "تم إلغاء الجلسة بنجاح.",
    "dashboard.student.upcoming.cancelError": "تعذر إلغاء الجلسة.",
    "dashboard.student.reviews.title": "قيّم الجلسات الأخيرة",
    "dashboard.student.reviews.description": "راجع جلساتك السابقة وساعد باقي الطلاب.",
    "dashboard.student.reviews.none": "لم تُكمل أي جلسات بعد.",
    "dashboard.student.reviews.rate": "قيّم الجلسة",
    "dashboard.student.reviews.reviewWith": "قيّم جلستك مع {{name}}",
    "dashboard.student.reviews.feedback": "ملاحظاتك مهمة.",
    "dashboard.student.reviews.rating": "التقييم",
    "dashboard.student.reviews.comment": "التعليق",
    "dashboard.student.reviews.placeholder": "أخبرنا عن تجربتك...",
    "dashboard.student.reviews.submit": "إرسال التقييم",
    "dashboard.student.reviews.submitting": "جاري الإرسال...",
    "dashboard.student.reviews.success": "تم إرسال التقييم بنجاح!",
    "dashboard.student.reviews.error": "تعذر إرسال التقييم.",
    "dashboard.teacher.profileSettings": "إعدادات الملف الشخصي",
    "dashboard.teacher.profileSubtitle": "حافظ على بياناتك التعليمية محدّثة للطلاب.",
    "dashboard.teacher.prefix": "اللقب",
    "dashboard.teacher.prefixPlaceholder": "اختر لقبًا",
    "dashboard.teacher.firstName": "الاسم الأول",
    "dashboard.teacher.middleName": "الاسم الأوسط",
    "dashboard.teacher.familyName": "اسم العائلة",
    "dashboard.teacher.phone": "رقم الهاتف",
    "dashboard.teacher.email": "البريد الإلكتروني",
    "dashboard.teacher.bio": "نبذة قصيرة",
    "dashboard.teacher.photoLabel": "صورة الملف الشخصي",
    "dashboard.teacher.photoSelected": "الملف المحدد",
    "dashboard.teacher.photoUpload": "ارفع صورة",
    "dashboard.teacher.photoReplace": "استبدل الصورة",
    "dashboard.teacher.photoRemove": "إزالة الصورة",
    "dashboard.teacher.photoHelper": "ستظهر هذه الصورة في بطاقة المعلم بعد موافقة فريق الإدارة.",
    "dashboard.teacher.photoAlt": "صورة المعلم",
    "dashboard.teacher.saving": "يتم الحفظ...",
    "dashboard.teacher.updateProfile": "تحديث الملف",
    "dashboard.teacher.profileUpdated": "تم تحديث بيانات الملف",
    "dashboard.teacher.subjectFormTitle": "تسجيل مادة جديدة",
    "dashboard.teacher.subjectFormSubtitle": "اعرض للطلاب المقررات التي يمكنك تدريسها والدرجات التي حققتها.",
    "dashboard.teacher.subjectApprovalNote": "تظهر المواد للطلاب بعد أن يعتمد فريق PeerEdu تقارير الدرجات المرفوعة.",
    "dashboard.teacher.subjectName": "اسم المادة",
    "dashboard.teacher.subjectCode": "رمز المادة",
    "dashboard.teacher.college": "الكلية / الجامعة",
    "dashboard.teacher.grade": "الدرجة المحققة",
    "dashboard.teacher.subjectListTitle": "المواد المسجلة",
    "dashboard.teacher.subjectSubmit": "إضافة المادة",
    "dashboard.teacher.subjectAdded": "تمت إضافة المادة إلى ملفك",
    "dashboard.teacher.subjectVerification.identity": "أؤكد أن اسمي الكامل ورقم الطالب واسم الكلية يظهرون في الإثبات المرفوع.",
    "dashboard.teacher.subjectVerification.grade": "أؤكد أن الدرجة المعروضة صحيحة وصادرة من كليتي.",
    "dashboard.teacher.subjectVerification.helper": "تأكد من أن المستند يوضح اسم كليتك وسنتك الأكاديمية.",
    "dashboard.teacher.subjectVerification.error": "يرجى تأكيد الخيارين قبل إضافة المادة.",
    "dashboard.teacher.gradeProof": "أرفق إثبات الدرجة",
    "dashboard.teacher.gradeProof.helper": "أرفق ملف PDF أو صورة واضحة تظهر درجة هذا المقرر (PDF/JPG/PNG بحد أقصى 10 ميجابايت).",
    "dashboard.teacher.gradeProof.selected": "الملف المحدد",
    "dashboard.teacher.gradeProof.error": "يرجى رفع تقرير الدرجات قبل إضافة هذه المادة.",
    "dashboard.teacher.availabilityTitle": "التوفر الأسبوعي",
    "dashboard.teacher.availabilityHelper": "حدد الأوقات التي يمكن للطلاب حجزها معك.",
    "dashboard.teacher.quickActions": "إجراءات سريعة",
    "dashboard.teacher.quickActions.settings": "الإعدادات",
    "dashboard.teacher.quickActions.availability": "إدارة التوفر",
    "dashboard.teacher.quickActions.sessions": "عرض جميع الجلسات",
    "dashboard.teacher.quickActions.analytics": "تحليلات مفصلة",
    "dashboard.teacher.hero.badge": "لوحة تحكم المعلم",
    "dashboard.teacher.hero.welcome": "مرحبًا بعودتك، {{name}}.",
    "dashboard.teacher.hero.subtitle": "تابع الطلبات الجديدة، التزاماتك القادمة، ونموك داخل PeerEdu.",
    "dashboard.teacher.hero.registerCta": "سجّل المواد",
    "dashboard.teacher.hero.spotlightTitle": "أضواء التدريس",
    "dashboard.teacher.hero.spotlightStatus": "بانتظار الموافقة",
    "dashboard.teacher.hero.spotlightDescription":
      "تظهر المواد هنا بعد أن يعتمد فريق الإدارة تقارير الدرجات التي ترفعها. أرسل كشف الدرجات من الإعدادات لفتح هذا القسم.",
    "dashboard.teacher.hero.pendingBadge": "معلّق",
    "dashboard.teacher.hero.manageProfile": "إدارة الملف",
    "dashboard.teacher.hero.registerSubjects": "تسجيل المواد",
    "dashboard.teacher.stats.requests": "طلبات جديدة",
    "dashboard.teacher.stats.requestsHelper": "بانتظار الرد",
    "dashboard.teacher.stats.upcoming": "جلسات قادمة",
    "dashboard.teacher.stats.upcomingHelper": "خلال 7 أيام",
    "dashboard.teacher.stats.total": "إجمالي الجلسات",
    "dashboard.teacher.stats.totalHelper": "مكتملة",
    "dashboard.teacher.stats.subjects": "موادي",
    "dashboard.teacher.stats.subjectsApproved": "مواد معتمدة",
    "dashboard.teacher.stats.subjectsPending": "ستظهر بعد اعتماد الإدارة",
    "dashboard.teacher.stats.pendingValue": "قيد الانتظار",
    "dashboard.teacher.stats.rating": "تقييمي",
    "dashboard.teacher.stats.ratingHelper": "من 5",
    "dashboard.teacher.stats.earnings": "الأرباح المتوقعة",
    "dashboard.teacher.stats.earningsHelper": "ر.ع",
    "dashboard.teacher.profileUpdateError": "تعذر تحديث ملفك. يرجى المحاولة مرة أخرى.",
    "dashboard.teacher.settings.title": "إعدادات المعلم",
    "dashboard.teacher.settings.subtitle": "اضبط ملفك التعليمي وابرز خبراتك أمام الطلاب.",
    "dashboard.teacher.preferences.title": "تفضيلات التدريس",
    "dashboard.teacher.preferences.description": "أطلع الطلاب على توافرك وأسلوبك في التعلم.",
    "dashboard.teacher.preferences.point1": "حدّث أوقاتك المتاحة من مدير التوفر.",
    "dashboard.teacher.preferences.point2": "استخدم تسجيل المواد لإبراز مساراتك الأقوى.",
    "dashboard.teacher.preferences.point3": "حافظ على صورة ملفك ونبذتك متسقة في جميع اللغات.",
    "availability.heading": "إدارة التوفر",
    "availability.day.sunday": "الأحد",
    "availability.day.monday": "الاثنين",
    "availability.day.tuesday": "الثلاثاء",
    "availability.day.wednesday": "الأربعاء",
    "availability.day.thursday": "الخميس",
    "availability.day.friday": "الجمعة",
    "availability.day.saturday": "السبت",
    "availability.empty": "لا توجد فترات بعد",
    "availability.dialog.add": "إضافة توفر",
    "availability.dialog.edit": "تعديل التوفر",
    "availability.dialog.start": "وقت البدء",
    "availability.dialog.end": "وقت الانتهاء",
    "availability.dialog.cancel": "إلغاء",
    "availability.dialog.save": "حفظ الفترة",
    "availability.dialog.deleteTitle": "حذف هذا التوفر؟",
    "availability.dialog.deleteDescription": "لا يمكن التراجع عن هذا الإجراء. سيُحذف هذا الوقت بشكل نهائي.",
    "availability.dialog.deleteConfirm": "حذف",
    "availability.error.missing": "يرجى إدخال وقت بداية ونهاية.",
    "availability.error.order": "يجب أن يكون وقت الانتهاء بعد وقت البدء.",
    "availability.toast.saveSuccess": "تم حفظ فترة التوفر.",
    "availability.toast.saveError": "تعذر حفظ فترة التوفر.",
    "availability.toast.updateSuccess": "تم تحديث فترة التوفر.",
    "availability.toast.updateError": "تعذر تحديث فترة التوفر.",
    "availability.toast.deleteSuccess": "تم حذف فترة التوفر.",
    "availability.toast.deleteError": "تعذر حذف فترة التوفر.",

    // Hero Section
    "hero.subtitle":
      "PeerEdu يربط طلاب الجامعات مع بعضهم البعض للتعلم من الأقران والتميز الأكاديمي. ابحث عن مدرسين خبراء أو شارك معرفتك مع الكسب - كل ذلك ضمن مجتمع تعليمي موثوق بين الأقران.",
    "hero.cta.primary": "ابدأ الآن",
    "hero.cta.secondary": "اعرف المزيد",

    // How It Works Section
    "works.title": "كيف يعمل PeerEdu",
    "works.subtitle": "بسيط وآمن وفعال للتعلم بين الأقران",
    "works.connect.title": "تواصل",
    "works.connect.desc": "ابحث عن المدرس أو الطالب المثالي بناءً على احتياجاتك الأكاديمية وجدولك الزمني",
    "works.learn.title": "تعلم",
    "works.learn.desc": "شارك في جلسات تدريس شخصية مصممة لمساعدتك على التفوق في دراستك",
    "works.excel.title": "تفوق",
    "works.excel.desc": "حقق أهدافك الأكاديمية مع بناء علاقات دائمة مع زملائك الطلاب",

    // Features Section
    "features.title": "لماذا تختار PeerEdu؟",
    "features.subtitle": "مبني من قبل الطلاب، للطلاب - بميزات مهمة",
    "features.expert.title": "مدرسون خبراء",
    "features.expert.desc": "تواصل مع الطلاب المتميزين أكاديمياً والذين يتفوقون في مواضيعهم",
    "features.flexible.title": "جدولة مرنة",
    "features.flexible.desc": "احجز جلسات تناسب جدولك الزمني مع نظام حجز سهل الاستخدام",
    "features.secure.title": "آمن ومحمي",
    "features.secure.desc": "ملفات طلابية موثقة ونظام دفع آمن لراحة البال",

    // Mission, Vision, Message
    "message.title": "رسالتنا",
    "message.content":
      "التعليم أقوى عندما يُشارك. نؤمن أن كل طالب لديه شيء قيم ليعلمه ويتعلمه. PeerEdu ينشئ مجتمعاً حيث تتدفق المعرفة بحرية، مما يعزز التميز الأكاديمي والروابط المعنوية.",
    "vision.title": "رؤيتنا",
    "vision.content":
      "أن نصبح منصة التعلم الرائدة بين الأقران في الشرق الأوسط، نمكن الطلاب من تحقيق التميز الأكاديمي من خلال التعلم التعاوني ومشاركة المعرفة.",
    "mission.title": "مهمتنا",
    "mission.content":
      "ربط طلاب الجامعات في جميع أنحاء عُمان، وخلق فرص للتعلم بين الأقران والدعم الأكاديمي والنمو الشخصي مع تعزيز ثقافة مشاركة المعرفة والتعاون.",

    // CEO Section
    "ceo.title": "تعرف على الرئيس التنفيذي",
    "ceo.subtitle": "قيادة الرؤية للتعليم بين الأقران في عُمان",
    "ceo.name": "محمد أشرف",
    "ceo.position": "المؤسس والرئيس التنفيذي",
    "ceo.bio1":
      "محمد حاصل على درجة البكالوريوس في تطوير تطبيقات البرمجيات من كلية يوتاس عبري. بشغف لتكنولوجيا التعليم وتمكين الطلاب، أسس PeerEdu لسد الفجوة بين الطلاب الذين يسعون للدعم الأكاديمي وأولئك المتفوقين في دراستهم.",
    "ceo.bio2":
      "رؤيته هي إنشاء نظام بيئي مستدام حيث تصبح مشاركة المعرفة جزءاً طبيعياً من الحياة الجامعية، مما يساعد الطلاب ليس فقط على تحقيق النجاح الأكاديمي ولكن أيضاً تطوير مهارات القيادة والإرشاد التي ستخدمهم طوال حياتهم المهنية.",

    // CTA Section
    "cta.title": "مستعد لبدء التعلم؟",
    "cta.subtitle":
      "انضم إلى آلاف الطلاب الذين يستخدمون PeerEdu بالفعل للتفوق في دراستهم. سواء كنت تحتاج مساعدة أو تريد مساعدة الآخرين، نحن نغطيك.",
    "cta.student": "انضم كطالب",
    "cta.tutor": "كن مدرساً",

    // Login Page
    "login.title": "تسجيل الدخول",
    "login.subtitle": "ادخل إلى حسابك في PeerEdu لمتابعة رحلة التعلم",
    "login.form.title": "تسجيل الدخول إلى حسابك",
    "login.form.description": "أدخل بريدك الإلكتروني وكلمة المرور للوصول إلى حسابك",
    "login.email": "البريد الجامعي",
    "login.password": "كلمة المرور",
    "login.remember": "تذكرني",
    "login.forgot": "نسيت كلمة المرور؟",
    "login.submit": "تسجيل الدخول",
    "login.loading": "جارٍ تسجيل الدخول...",
    "login.signup": "ليس لديك حساب؟ أنشئ حساباً هنا",

    // Register Page
    "register.title": "إنشاء حساب",
    "register.subtitle": "ابدأ رحلة التعلم بين الأقران اليوم",
    "register.form.title": "التسجيل في PeerEdu",
    "register.form.description": "أنشئ حسابك للتواصل مع زملائك الطلاب",
    "register.role.title": "التسجيل كـ",
    "register.role.student": "طالب",
    "register.role.teacher": "مدرس",
    "register.firstName": "الاسم الأول",
    "register.middleName": "الاسم الأوسط",
    "register.familyName": "اسم العائلة",
    "register.phone": "رقم الهاتف",
    "register.email": "البريد الإلكتروني التعليمي",
    "register.university": "الكلية/الجامعة",
    "register.yearOfStudy": "سنة الدراسة",
    "register.password": "كلمة المرور",
    "register.confirmPassword": "تأكيد كلمة المرور",
    "register.terms": "أوافق على شروط الخدمة وسياسة الخصوصية",
    "register.submit": "تسجيل",
    "register.loading": "جارٍ إنشاء الحساب...",
    "register.signin": "لديك حساب بالفعل؟ سجل دخولك هنا",
    "register.continue": "أو تابع مع",
    "register.google": "جوجل",
    "register.twitter": "تويتر",
    "register.placeholder.firstName": "الاسم الأول",
    "register.placeholder.middleName": "الاسم الأوسط",
    "register.placeholder.familyName": "اسم العائلة",
    "register.placeholder.phone": "+968",
    "register.placeholder.email": "أدخل بريدك الإلكتروني التعليمي",
    "register.placeholder.university": "اختر كليتك/جامعتك",
    "register.placeholder.yearOfStudy": "اختر سنة دراستك",
    "register.placeholder.password": "أنشئ كلمة مرور",
    "register.placeholder.confirmPassword": "أكد كلمة المرور",
    "register.gradeUpload": "قم برفع آخر تقرير درجات لك",
    "register.gradeUpload.helper": "الصيغ المقبولة: ملف PDF أو صورة واضحة (بحد أقصى 10 ميجابايت).",
    "register.gradeUpload.selected": "الملف المحدد",
    "register.checkbox.gradeAuthentic": "أؤكد أن تقرير الدرجات هذا حقيقي وصادر من كليتي.",
    "register.checkbox.gradeIdentity": "اسمي الكامل ورقم الطالب يظهران في التقرير المرفوع.",
    "register.checkbox.reportDetails": "تأكد أن اسم الكلية وسنة الدراسة يظهران في المستند.",
    "register.university.utas": "جامعة التقنية والعلوم التطبيقية",
    "register.university.squ": "جامعة السلطان قابوس",
    "register.university.german": "الجامعة الألمانية للتكنولوجيا",
    "register.university.nizwa": "جامعة نزوى",
    "register.university.dhofar": "جامعة ظفار",
    "register.university.muscat": "جامعة مسقط",
    "register.university.oman": "جامعة عمان",
    "register.university.utas.ibri": "جامعة التقنية والعلوم التطبيقية - عبري",
    "register.university.utas.muscat": "جامعة التقنية والعلوم التطبيقية - مسقط",
    "register.university.utas.sohar": "جامعة التقنية والعلوم التطبيقية - صحار",
    "register.university.utas.salalah": "جامعة التقنية والعلوم التطبيقية - صلالة",
    "register.university.utas.nizwa": "جامعة التقنية والعلوم التطبيقية - نزوى",
    "register.university.utas.general": "جامعة التقنية والعلوم التطبيقية (عام)",
    "register.university.utas.shinas": "جامعة التقنية والعلوم التطبيقية - شناص",
    "register.university.utas.sur": "جامعة التقنية والعلوم التطبيقية - صور",
    "register.university.utas.almusannah": "جامعة التقنية والعلوم التطبيقية - المصنعة",
    "register.university.utas.ibra": "جامعة التقنية والعلوم التطبيقية - إبراء",
    "register.university.utas.rustaq": "جامعة التقنية والعلوم التطبيقية - الرستاق",
    "register.university.buraimi": "جامعة البريمي",
    "register.university.sohar": "جامعة صحار",
    "register.university.asharqiyah": "جامعة الشرقية",
    "register.university.national": "الجامعة الوطنية للعلوم والتكنولوجيا",
    "register.university.majan": "كلية مجان الجامعية",
    "register.university.modern": "الكلية الحديثة للتجارة والعلوم",
    "register.university.middleeast": "كلية الشرق الأوسط",
    "register.university.arabopen": "الجامعة العربية المفتوحة - عمان",
    "register.university.tourism": "كلية عمان للسياحة",
    "register.university.healthsciences": "كلية عمان للعلوم الصحية",
    "register.university.maritime": "الكلية البحرية الدولية - عمان",
    "register.university.dental": "كلية عمان لطب الأسنان",
    "register.university.alzahra": "كلية الزهراء للبنات",
    "register.university.gulf": "كلية الخليج",
    "register.university.bayan": "كلية البيان",
    "register.university.law": "كلية عمان للحقوق",
    "register.university.other": "أخرى",
    "register.year.foundation1": "المستوى التأسيسي الأول",
    "register.year.foundation2": "المستوى التأسيسي الثاني",
    "register.year.foundation3": "المستوى التأسيسي الثالث",
    "register.year.foundation4": "المستوى التأسيسي الرابع",
    "register.year.study1": "السنة الأولى",
    "register.year.study2": "السنة الثانية",
    "register.year.study3": "السنة الثالثة",
    "register.year.study4": "السنة الرابعة",
    "register.year.graduate": "خريج جديد",

    // Tutors Page
    "tutors.nav.back": "العودة إلى لوحة التحكم",
    "tutors.nav.tagline": "بحث المعلمين",
    "tutors.hero.badge": "مطابقة ذكية",
    "tutors.title": "اعثر على المعلمين حسب الكلية والمقرر",
    "tutors.subtitle": "اختر كليتك، أضف رمز المقرر، وسترى المعلمين الجاهزين لدعمك.",
    "tutors.hero.hint": "تحتاج إلى نتيجة أدق؟",
    "tutors.hero.hintDetail": "عدّل المرشحات في أي وقت لتحصل على تحديث فوري.",
    "tutors.filters.title": "تصفية المعلمين",
    "tutors.filters.description": "ابدأ بالكلية ثم أضف تفاصيل المقرر.",
    "tutors.filters.university": "الكلية",
    "tutors.filters.university.placeholder": "اختر كلية",
    "tutors.filters.subjectCode": "رمز المقرر",
    "tutors.filters.subjectCode.placeholder": "مثال: ENG201",
    "tutors.filters.subjectName": "اسم المقرر",
    "tutors.filters.subjectName.placeholder": "مثال: الكتابة الأكاديمية",
    "tutors.filters.teacherName": "اسم المعلم",
    "tutors.filters.teacherName.placeholder": "مثال: علي الحبسي",
    "tutors.filters.optional": "اختياري",
    "tutors.mobile.button": "مرشحات",
    "tutors.mobile.title": "تحسين النتائج",
    "tutors.results.preheading": "قائمة المطابقة",
    "tutors.results.heading": "المعلمون المتاحون",
    "tutors.results.caption": "تتحدث النتائج تلقائيًا عند تعديل المرشحات.",
    "tutors.results.error.title": "تعذر تحميل قائمة المعلمين",
    "tutors.results.error.description": "يرجى تحديث الصفحة أو تعديل المرشحات ثم المحاولة مرة أخرى.",
    "tutors.results.empty.title": "لا يوجد معلمون لهذا البحث",
    "tutors.results.empty.description": "غيّر بيانات الكلية أو المقرر لرؤية المزيد من المعلمين.",
    "tutors.results.showing": "عرض",
    "tutors.results.of": "من",
    "tutors.results.tutors": "معلمين",
    "tutors.pagination.prev": "الصفحة السابقة",
    "tutors.pagination.next": "الصفحة التالية",
    "tutor.card.reviews": "تقييمات",
    "tutor.card.perHour": "لكل ساعة",
    "tutor.card.sessionSummary.prefix": "استنادًا إلى",
    "tutor.card.sessionSummary.suffix": "جلسات مكتملة.",
    "tutor.card.viewProfile": "عرض الملف",
    "tutor.card.bookNow": "احجز الآن",

    // About Page
    "about.title": "تمكين الطلاب من خلال التعلم بين الأقران",
    "about.subtitle":
      "تأسست بالإيمان أن أفضل تعلم يحدث عندما يعلم الطلاب الطلاب، PeerEdu تثور التعليم في عُمان من خلال إنشاء روابط معنوية بين طلاب الجامعات.",
    "about.story.title": "قصتنا",
    "about.story.subtitle": "كيف وُلد PeerEdu",
    "about.story.p1":
      "وُلد PeerEdu من ملاحظة بسيطة: طلاب الجامعات غالباً ما يكافحون للعثور على الدعم الأكاديمي المناسب، بينما العديد من الطلاب الموهوبين لديهم معرفة لمشاركتها لكن يفتقرون إلى المنصة للقيام بذلك بفعالية.",
    "about.story.p2":
      "مؤسسنا، محمد أشرف، عاش هذا بنفسه خلال دراسته في تطوير تطبيقات البرمجيات في كلية يوتاس عبري. لاحظ أن التعلم بين الأقران لم يكن فقط أكثر قابلية للفهم وإمكانية الوصول ولكن غالباً أكثر فعالية من طرق التدريس التقليدية.",
    "about.story.p3":
      "اليوم، PeerEdu يعمل كجسر يربط الطلاب في جميع أنحاء عُمان، مما يعزز مجتمعاً حيث يتحقق التميز الأكاديمي من خلال التعاون والدعم المتبادل والمعرفة المشتركة.",
    "about.foundation.title": "أساسنا",
    "about.foundation.subtitle": "المبادئ التي توجه كل ما نقوم به",
    "about.mission.title": "المهمة",
    "about.mission.content":
      "ربط طلاب الجامعات في جميع أنحاء عُمان، وخلق فرص للتعلم بين الأقران والدعم الأكاديمي والنمو الشخصي مع تعزيز ثقافة مشاركة المعرفة والتعاون.",
    "about.vision.title": "الرؤية",
    "about.vision.content":
      "أن نصبح منصة التعلم الرائدة بين الأقران في الشرق الأوسط، نمكن الطلاب من تحقيق التميز الأكاديمي من خلال التعلم التعاوني ومشاركة المعرفة.",
    "about.values.title": "القيم",
    "about.values.content":
      "التميز والتعاون والنزاهة وإمكانية الوصول. نؤمن أن التعليم يجب أن يكون شاملاً وداعماً ومدفوعاً بالاهتمام الحقيقي بنجاح الطلاب.",
    "about.different.title": "ما يجعلنا مختلفين",
    "about.different.subtitle": "لماذا يختار الطلاب PeerEdu على التدريس التقليدي",
    "about.peer.title": "التواصل بين الأقران",
    "about.peer.desc": "تعلم من زملائك الطلاب الذين أتقنوا مؤخراً نفس المفاهيم التي تكافح معها",
    "about.flexible.title": "مرن وبأسعار معقولة",
    "about.flexible.desc": "أكثر بأسعار معقولة من التدريس المهني مع جدولة تعمل حول حياة الطلاب",
    "about.safe.title": "آمن وموثق",
    "about.safe.desc": "جميع المدرسين طلاب جامعيون موثقون بتميز أكاديمي مثبت",
    "about.expertise.title": "خبرة في المواضيع",
    "about.expertise.desc": "ابحث عن مدرسين يتفوقون في مقرراتك المحددة ويفهمون منهجك",
    "about.results.title": "نتائج مثبتة",
    "about.results.desc": "الطلاب يبلغون عن تحسن في الدرجات وفهم أفضل من خلال التعلم بين الأقران",
    "about.growth.title": "نمو متبادل",
    "about.growth.desc": "كل من المدرسين والطلاب يستفيدون - تعلم مع الكسب، علم مع تعزيز المعرفة",
    "about.leadership.title": "القيادة",
    "about.leadership.subtitle": "تعرف على الفريق وراء PeerEdu",
    "about.ceo.bio1":
      "محمد حاصل على درجة البكالوريوس في تطوير تطبيقات البرمجيات من كلية يوتاس عبري. رحلته الأكاديمية أشعلت فكرة PeerEdu عندما أدرك الإمكانات غير المستغلة للتعلم بين الأقران في البيئات الجامعية.",
    "about.ceo.bio2":
      "بفهم عميق لكل من التكنولوجيا والتعليم، محمد يجمع خبرته التقنية مع شغفه لتمكين الطلاب لإنشاء حلول مبتكرة تجعل التعلم أكثر إمكانية وفعالية.",
    "about.ceo.bio3":
      "رؤيته تمتد إلى ما هو أبعد من مجرد ربط الطلاب - يهدف إلى بناء نظام بيئي مستدام حيث تصبح مشاركة المعرفة جزءاً لا يتجزأ من الثقافة الجامعية، إعداد الطلاب ليس فقط للنجاح الأكاديمي ولكن للتعلم مدى الحياة والقيادة.",
    "about.impact.title": "تأثيرنا",
    "about.impact.subtitle": "مجتمع متنامي من الطلاب يساعدون الطلاب على النجاح",
    "about.stats.students": "طلاب نشطون",
    "about.stats.sessions": "جلسات مكتملة",
    "about.stats.subjects": "مواضيع مغطاة",
    "about.stats.satisfaction": "معدل الرضا",
    "about.join.title": "انضم إلى مجتمعنا",
    "about.join.subtitle":
      "كن جزءاً من ثورة التعلم بين الأقران. سواء كنت تحتاج مساعدة أو تريد مساعدة الآخرين، PeerEdu هو منصتك للنجاح الأكاديمي.",
    "about.join.cta": "ابدأ اليوم",
    "about.join.back": "العودة للرئيسية",

    // Footer
    "footer.contact": "اتصل بنا",
    "footer.description": "ربط طلاب الجامعات للتعلم بين الأقران والتميز الأكاديمي.",
    "footer.support": "الدعم",
    "footer.faq": "الأسئلة الشائعة",
    "footer.policy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.rights": "© 2025 PeerEdu. جميع الحقوق محفوظة.",
    "footer.followUs": "تابعنا",

    // Forgot Password Page
    "forgotPassword.title": "نسيت كلمة المرور",
    "forgotPassword.subtitle": "أدخل بريدك الإلكتروني لاستلام رابط إعادة التعيين",
    "forgotPassword.email": "البريد الإلكتروني",
    "forgotPassword.submit": "إرسال رابط إعادة التعيين",
    "forgotPassword.loading": "جار الإرسال...",
    "forgotPassword.success.title": "تحقق من بريدك الإلكتروني",
    "forgotPassword.success.message":
      "تم إرسال رابط إعادة تعيين كلمة المرور إلى عنوان بريدك الإلكتروني. يرجى التحقق من صندوق الوارد الخاص بك.",
    "forgotPassword.backToLogin": "العودة إلى تسجيل الدخول",

    // Reset Password Page
    "resetPassword.title": "إعادة تعيين كلمة المرور",
    "resetPassword.subtitle": "أنشئ كلمة مرور جديدة وقوية لحسابك.",
    "resetPassword.password": "كلمة المرور الجديدة",
    "resetPassword.confirmPassword": "تأكيد كلمة المرور الجديدة",
    "resetPassword.submit": "تعيين كلمة المرور الجديدة",
    "resetPassword.loading": "جار الإعادة...",
    "resetPassword.success.title": "تم إعادة تعيين كلمة المرور!",
    "resetPassword.success.message":
      "تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.",
    "resetPassword.goToLogin": "الذهاب إلى تسجيل الدخول",
    "resetPassword.invalid.title": "رابط غير صالح",
    "resetPassword.invalid.message":
      "رابط إعادة تعيين كلمة المرور هذا غير صالح أو انتهت صلاحيته. يرجى طلب رابط جديد.",
    "resetPassword.invalid.requestNew": "طلب رابط جديد",
    "resetPassword.strength.weak": "ضعيف",
    "resetPassword.strength.medium": "متوسط",
    "resetPassword.strength.strong": "قوي",
    "resetPassword.error.mismatch": "كلمتا المرور غير متطابقتين",
    "resetPassword.error.length": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "resetPassword.error.case": "يجب أن تحتوي على حرف كبير واحد على الأقل",
    "resetPassword.error.number": "يجب أن تحتوي على رقم واحد على الأقل",
    "resetPassword.error.special": "يجب أن تحتوي على رمز خاص واحد على الأقل",

    // Password Changed Email
    "passwordChanged.subject": "تم تغيير كلمة المرور الخاصة بك في PeerEdu",
    "passwordChanged.title": "تم تغيير كلمة المرور بنجاح",
    "passwordChanged.greeting": "مرحباً {name}،",
    "passwordChanged.message":
      "هذا البريد الإلكتروني يؤكد أنه تم تغيير كلمة المرور لحسابك في PeerEdu بنجاح.",
    "passwordChanged.warning":
      "إذا لم تكن أنت من قام بهذا التغيير، يرجى الاتصال بفريق الدعم لدينا على الفور لتأمين حسابك.",
    "passwordChanged.contactSupport": "اتصل بالدعم",

    // Admin Dashboard
    "admin.dashboard.title": "لوحة تحكم المشرف",
    "admin.dashboard.subtitle": "نظرة عامة على منصة PeerEdu.",
    "admin.stats.totalUsers": "إجمالي المستخدمين",
    "admin.stats.students": "طلاب",
    "admin.stats.teachers": "معلمون",
    "admin.stats.admins": "مشرفون",
    "admin.stats.approvedTutors": "المعلمون المعتمدون",
    "admin.stats.pendingTutors": "المعلمون المعلقون",
    "admin.stats.totalBookings": "إجمالي الحجوزات",
    "admin.stats.pending": "معلقة",
    "admin.stats.confirmed": "مؤكدة",
    "admin.stats.completed": "مكتملة",
    "admin.stats.cancelled": "ملغاة",
    "admin.stats.totalRevenue": "إجمالي الإيرادات",
    "admin.stats.userGrowth": "نمو المستخدمين (30 يوم)",
    "admin.pendingApprovals.title": "طلبات المعلمين المعلقة",
    "admin.pendingApprovals.tutor": "المعلم",
    "admin.pendingApprovals.university": "الجامعة",
    "admin.pendingApprovals.subjects": "التخصصات",
    "admin.pendingApprovals.rate": "السعر",
    "admin.pendingApprovals.registered": "تاريخ التسجيل",
    "admin.pendingApprovals.actions": "الإجراءات",
    "admin.pendingApprovals.viewProfile": "عرض الملف الكامل",
    "admin.pendingApprovals.approve": "قبول",
    "admin.pendingApprovals.reject": "رفض",
    "admin.pendingApprovals.empty": "لا توجد طلبات معلمين معلقة حالياً.",
    "admin.pendingStudents.title": "حسابات الطلاب المعلقة",
    "admin.pendingStudents.description": "راجع وفعل حسابات الطلاب الجديدة.",
    "admin.pendingStudents.name": "الطالب",
    "admin.pendingStudents.email": "البريد الإلكتروني",
    "admin.pendingStudents.university": "الجامعة",
    "admin.pendingStudents.joined": "تاريخ التسجيل",
    "admin.pendingStudents.actions": "الإجراءات",
    "admin.pendingStudents.empty": "لا توجد حسابات طلاب بانتظار الموافقة.",
    "admin.subjectApprovals.title": "طلبات المواد",
    "admin.subjectApprovals.description": "معلمون بانتظار اعتماد المواد التي سجلوها.",
    "admin.subjectApprovals.empty": "لا توجد طلبات مواد معلقة حالياً.",
    "admin.subjectApprovals.noteLabel": "ملاحظة داخلية",
    "admin.subjectApprovals.notePlaceholder": "ملاحظة اختيارية للمشرف (لا تظهر للمعلم)",
    "admin.emptyState.generic": "لا يوجد أي عناصر للمراجعة حالياً.",
    "admin.recentUsers.title": "المستخدمون الجدد",
    "admin.recentUsers.name": "الاسم",
    "admin.recentUsers.email": "البريد الإلكتروني",
    "admin.recentUsers.role": "الدور",
    "admin.recentUsers.joined": "تاريخ الانضمام",
    "admin.recentBookings.title": "الحجوزات الأخيرة",
    "admin.recentBookings.student": "الطالب",
    "admin.recentBookings.tutor": "المعلم",
    "admin.recentBookings.status": "الحالة",
    "admin.recentBookings.date": "التاريخ",
    "admin.charts.userGrowthTitle": "المستخدمون الجدد (آخر 30 يومًا)",
    "admin.charts.bookingsStatusTitle": "الحجوزات حسب الحالة",
    "admin.charts.revenueTitle": "الإيرادات (آخر 7 أيام)",
    "admin.quickActions.title": "إجراءات سريعة",
    "admin.quickActions.manageUsers": "إدارة المستخدمين",
    "admin.quickActions.manageTutors": "إدارة المعلمين",
    "admin.quickActions.allBookings": "كل الحجوزات",
    "admin.quickActions.reports": "التقارير",
    "admin.quickActions.settings": "الإعدادات",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const stored = localStorage.getItem(LANGUAGE_COOKIE)
    const cookieLanguage = getCookieLanguage()
    const nextLanguage = resolveLanguage(stored ?? cookieLanguage ?? undefined)
    setLanguage(nextLanguage)
    document.documentElement.lang = nextLanguage
    document.documentElement.dir = nextLanguage === "ar" ? "rtl" : "ltr"
    setLanguageCookie(nextLanguage)
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem(LANGUAGE_COOKIE, lang)
    setLanguageCookie(lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

function getCookieLanguage(): Language | null {
  if (typeof document === "undefined") return null
  const match = document.cookie
    .split(";")
    .map((segment) => segment.trim())
    .find((segment) => segment.startsWith(`${LANGUAGE_COOKIE}=`))
  if (!match) return null
  const value = match.split("=")[1]
  return isSupportedLanguage(value) ? value : null
}

function setLanguageCookie(lang: Language) {
  if (typeof document === "undefined") return
  document.cookie = `${LANGUAGE_COOKIE}=${lang}; path=/; max-age=${LANGUAGE_COOKIE_MAX_AGE}`
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
